### PR TITLE
Preparing for NPM release

### LINKED ISSUE #11: Put it on NPM
I would really like to have this module in Node. Thanks!

### PR DESCRIPTION
**Pull request by alessioalex**
Closes #11

### CODE REVIEW

**Comment by addyosmani** [comment]
Thanks a ton for getting this all setup. Landing now!

**Comment by addyosmani** [comment]
This has been pushed to npm. I think one thing that would be useful to do is flesh out the readme with some examples and use cases. The source behind the project has changed a little since I wrote-up http://addyosmani.com/blog/faster-javascript-memoization/, but just walking through how to use it would be helpful.

I'll try to get around to this, otherwise PRs are always welcome :)

**Comment by alessioalex** [comment]
Yup, I was also thinking of updating the tests so they can be run in Node as well as in the browser.

**Comment by addyosmani** [comment]
That would be amazing <3

**Pull request merged**
